### ISSUE TITLE
Fix checklist issues

### ISSUE THREAD

**Issue by jpike88** [streaka/plantguard-issues#16]
- [x] Editable title that selects on load

- [x] Button for admin and above (Assign Checklist)
- [x] Dropdown to select one, or add checklist.

- [x] Button for everyone (Begin Checklist)
- [x] If no checklist, "There are no checklists assigned to this plant" with dropdown to select one, or add checklist.
- [x] If checklist, fire it up

Builder
- [ ] Add button for new section
- [x] Add button for new checklist item
- [ ] When complete, give action to then begin the checklist

**Comment by jpike88** [comment]
@markstreaka
