### ISSUE TITLE
Split checklist into operations / service

### ISSUE THREAD

**Issue by jpike88** [streaka/plantguard-issues#177]

**Comment by alexkingma1** [comment]
The general idea is that, under the hood, 'checklist' should refer to pre-starts. Pre-starts have specific functionality associated with Danger/Maintenance warning dialogs, and task creation upon submission. The purpose of a pre-start is to be completed before each use of a plant, and to warn of any unsuitable aspects (represented by tasks) and force acknowledgement of responsibility of the one completing the checklist.

Services are separate kinds of forms, which may or may not contain checklist-type fields. (Not sure exactly what a service contains at this stage.) A service is intended to be a passive record, used for look-up and proof of completion. At this stage, services have no direct effect on completion except to update the hours and distance etc. parameters for a plant.

In future, feedback/review forms may come into play, which are intended to operate on a supplier, or their plant. (Issue 242) These will be separate from checklists and services both, though again some elements may be similar between them.

- [ ] the Service Schedules menu item becomes Services, with two tabs for viewing and managing service forms, in addition to the existing content regarding complex scheduling logic.
- [ ] the Checklists menu item becomes Pre-Starts. The manage tab for this page should only show 'checklist' forms -- i.e. pre-starts, and not services or other template types.
- [ ] logging and assigning services only uses service templates.
- [ ] assigning and beginning checklists only uses 'checklist' type templates.
- [ ] the builder has an option to create both services and pre-start forms, with this being a selectable option somewhere at the top of the form, perhaps as a first, separate element. This selectable value is preset when choosing 'create pre-start checklist' or 'create service checklist' in the applicable pages. In this way, a checklist can be switched between a service or a pre-start by editing the checklist in the builder.
