### ISSUE TITLE
BUG - Service & Checklist Tweaks

### ISSUE THREAD

**Issue by LachiePenn** [streaka/plantguard-issues#293]
Using JPS Plumbing as the example account.
A couple of Tweaks

- [x] A completed Service is showing in Checklist History. Please see Video: http://streaka.testing.videos.s3.amazonaws.com/screencast_2017-06-21_15-42-27.mp4
Would be good to have a Service show under a History Tab in Services Menu
![service history in checklist](https://user-images.githubusercontent.com/25288888/27369336-dabe7d0a-569a-11e7-8cff-a8ae60328597.png)

- [x] Can't view a Service or Checklist in the Activity Log of Plant View. Please see video: http://streaka.testing.videos.s3.amazonaws.com/screencast_2017-06-21_15-49-43.mp4
The PDF doesn't download and if there is files associated with a service - how are these going to be viewed?
![activity log - view menu](https://user-images.githubusercontent.com/25288888/27369330-d427a1c4-569a-11e7-9407-3712fefbc659.png)

- [x] The Sub-Menu for Checklists and Services (Not a BUG), Mark informs me this is changing. Please see video from me: http://streaka.testing.videos.s3.amazonaws.com/screencast_2017-06-21_17-01-18.mp4
Changing the order of these to have the most used on top (or whatever you are planning on doing) and we are going to try and get users just to do Pre-Starts and Log Services - NOT get caught in Service Regimes for now - so Assign Service in its current form is not useful.
![sub menu](https://user-images.githubusercontent.com/25288888/27371624-e2f29a56-56a4-11e7-990c-19413869b3c1.png)

- [x] Question - are notifications turned on for next Services Due?
