### ISSUE TITLE
Checklist upgrades

### ISSUE THREAD

**Issue by jpike88** [streaka/plantguard-issues#33]
- [x] Danger needs to stop the checklist from being submitted, creates message saying ‘this checklist cannot be completed, please force flag’. Bonus points if it fails validation too with a similar message underneath that field.

**Multiple checklist support**

- [x] We need a checklists table now, with an appropriate mapping table from plant to checklist. These are all checklists that are internal (i.e. supplier managed), and come in two flavours:

- [x] We need to be able to choose a checklist to begin every time 'Begin Checklist' is hit.

- [x] When assigning a checklist, we want to see currently assigned checklists, as well as be able to manage

Two types of checklists

- Service checklist (hybrid of a checklist + configure next service)
- Pre-start checklist (hybrid of a checklist + simple hour/distance entry element)
